services:
  robo_consulta_cadastral:
    container_name: consulta_cadastral_cnpj_sp
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      TZ: Etc/GMT+4
    networks:
      consulta-cadastral-rede:
        ipv4_address: 10.36.0.10
    volumes:
      - consulta-cadastral-data:/app/logs

volumes:
  consulta-cadastral-data:

networks:
  consulta-cadastral-rede:
    driver: bridge
    ipam:
      config:
        - subnet: 10.36.0.0/16
          gateway: 10.36.0.1
